### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [MJulia23/grid-template#1]
1)
Внешний вид при наведении не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/96446332-f4793a80-1219-11eb-8f42-d16c8e3a8696.png)

2)
неправильное положение меню
![image](https://user-images.githubusercontent.com/8464662/96446581-1672bd00-121a-11eb-98c3-85257295c6e5.png)

3)
неправильная высота блоков
![image](https://user-images.githubusercontent.com/8464662/96446747-212d5200-121a-11eb-8f70-732cca3fdd6a.png)
![image](https://user-images.githubusercontent.com/8464662/96446968-30ac9b00-121a-11eb-95ba-d9d19d812c3d.png)

4)
неправильный размер шрифта
![image](https://user-images.githubusercontent.com/8464662/96447234-47eb8880-121a-11eb-8e5b-b5381fee290d.png)

5)
неправильные отступы.
проверяйте для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/96447298-5cc81c00-121a-11eb-91ba-d42a73785a15.png)

**Comment by MJulia23** [comment]
Исправила ошибки
https://mjulia23.github.io/grid-template/

**Comment by Alecto** [comment]
3 - не исправлено

**Comment by MJulia23** [comment]
![а](https://user-images.githubusercontent.com/69385739/97033265-bfe3e680-156b-11eb-8468-b76c6bc598be.png)
![в](https://user-images.githubusercontent.com/69385739/97033273-c1adaa00-156b-11eb-931d-e35d4a820c8c.png)
Исправила, только не пойму, почему при открытии с ноута, ошибки нет, а с гита все так же.

**Comment by Alecto** [comment]
чего не знаю, того не знаю.
проверяйте, выполняется ли коммит и дальше дебажте уже то, что выгрузили на
гит

пт, 23 жовт. 2020 о 20:13 Julia <notifications@github.com> пише:

**Comment by MJulia23** [comment]
Все делала по порядку. Не знаю почему сразу не применились изменения, сейчас зашла и все ок!

**Comment by Alecto** [comment]
появился горизонтальный скрол
![image](https://user-images.githubusercontent.com/8464662/97069247-af695580-15d7-11eb-997e-78a99f5aeb7b.png)

**Comment by MJulia23** [comment]
исправила

**Comment by Alecto** [comment]
отлично, работа принята )
только из письма непонятно, кому ставить работу.

сб, 24 жовт. 2020 о 09:45 Julia <notifications@github.com> пише:

**Comment by MJulia23** [comment]
SkillUp FrontEnd. Соцкова Юлия, сб/вс 12-00 SkillUp FrontEnd

**Comment by MJulia23** [comment]
SkillUp FrontEnd. Соцкова Юлия, сб/вс 12-00 SkillUp FrontEnd

сб, 24 окт. 2020 г. в 14:13, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
спасибо.
отметил вашу работу

сб, 24 жовт. 2020 о 17:08 Julia <notifications@github.com> пише:
